<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="tests.commands.test_api_error.APIErrorTest" tests="7" file="tests/commands/test_api_error.py" time="3.200" timestamp="2025-06-24T18:17:23" failures="0" errors="0" skipped="0">
	<testcase classname="tests.commands.test_api_error.APIErrorTest" name="test_all_workflow_when_server_down" time="0.451" timestamp="2025-06-24T18:17:20" file="tests/commands/test_api_error.py" line="377"/>
	<testcase classname="tests.commands.test_api_error.APIErrorTest" name="test_record_build" time="1.019" timestamp="2025-06-24T18:17:21" file="tests/commands/test_api_error.py" line="103"/>
	<testcase classname="tests.commands.test_api_error.APIErrorTest" name="test_record_commit" time="1.396" timestamp="2025-06-24T18:17:23" file="tests/commands/test_api_error.py" line="85"/>
	<testcase classname="tests.commands.test_api_error.APIErrorTest" name="test_record_session" time="0.061" timestamp="2025-06-24T18:17:23" file="tests/commands/test_api_error.py" line="173"/>
	<testcase classname="tests.commands.test_api_error.APIErrorTest" name="test_record_tests" time="0.048" timestamp="2025-06-24T18:17:23" file="tests/commands/test_api_error.py" line="316"/>
	<testcase classname="tests.commands.test_api_error.APIErrorTest" name="test_subset" time="0.137" timestamp="2025-06-24T18:17:23" file="tests/commands/test_api_error.py" line="237"/>
	<testcase classname="tests.commands.test_api_error.APIErrorTest" name="test_verify" time="0.088" timestamp="2025-06-24T18:17:23" file="tests/commands/test_api_error.py" line="57"/>
</testsuite>
